# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_display', '0003_kulcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARATHA',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpage_display.Menu')),
            ],
            bases=('webpage_display.menu',),
        ),
    ]
